trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_SERVER: 'https://sonar-dev.supervity.ai'
  SONARQUBE_TOKEN: 'sqa_18ca7a4a75620b175378099dc7730a1eddf2a3b6'
  SONAR_PROJECT_KEY: 'test'
  SONAR_PROJECT_NAME: 'test'
  SONAR_PROJECT_VERSION: '1.0'

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'test'
    cliProjectName: 'test'
    cliSources: '.'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'




- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'