trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_SERVER: 'https://sonar-dev.supervity.ai'
  SONARQUBE_TOKEN: '$(sqa_18ca7a4a75620b175378099dc7730a1eddf2a3b6)'
  SONAR_PROJECT_KEY: 'Infra-Test_Infra-Test_c5e09591-38a9-4945-855d-ef8425949b9b'
  SONAR_PROJECT_NAME: 'walmart-python'
  SONAR_PROJECT_VERSION: '1.0'

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Infra-Test_Infra-Test_c5e09591-38a9-4945-855d-ef8425949b9b'
    cliProjectName: 'walmart-python'
    cliSources: '.'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'




- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'