trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_SERVER: 'https://sonar-dev.supervity.ai/'
  SONARQUBE_TOKEN: 'sqa_18ca7a4a75620b175378099dc7730a1eddf2a3b6'  # Make sure this is securely stored in Azure DevOps
  SONAR_PROJECT_KEY: 'Infra-Test_Infra-Test_c5e09591-38a9-4945-855d-ef8425949b9b'
  SONAR_PROJECT_NAME: 'python-Test'
  SONAR_PROJECT_VERSION: '1.0'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt.txt
  displayName: 'Install dependencies'
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Infra-Test_Infra-Test_c5e09591-38a9-4945-855d-ef8425949b9b'
    cliSources: '.'
- script: |
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
    unzip sonar-scanner-cli-4.7.0.2747-linux.zip
    export PATH=$(pwd)/sonar-scanner-4.7.0.2747-linux/bin:$PATH
  displayName: 'Install and Set up SonarQube Scanner'

- script: |
    sonar-scanner \
      -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
      -Dsonar.projectName=$(SONAR_PROJECT_NAME) \
      -Dsonar.projectVersion=$(SONAR_PROJECT_VERSION) \
      -Dsonar.sources=. \
      -Dsonar.host.url=$(SONARQUBE_SERVER) \
      -Dsonar.login=$(SONARQUBE_TOKEN)
  displayName: 'Run SonarQube Analysis'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'
