trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_SERVER: 'https://sonar-dev.supervity.ai'
  SONARQUBE_TOKEN: 'sqa_18ca7a4a75620b175378099dc7730a1eddf2a3b6'  # Ensure this is securely stored in Azure DevOps
  SONAR_PROJECT_KEY: 'python-test'
  SONAR_PROJECT_NAME: 'python-test'
  SONAR_PROJECT_VERSION: '1.0'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt.txt
  displayName: 'Install dependencies'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'  # Ensure this matches the name of your SonarQube service connection in Azure DevOps
    scannerMode: 'CLI'
    configMode: 'file'
    configFile: 'sonar-project.properties'
    cliProjectKey: '$(SONAR_PROJECT_KEY)'
    cliProjectName: '$(SONAR_PROJECT_NAME)'
    cliSources: '.'
    extraProperties: |
      sonar.python.version=3.x
      sonar.projectVersion=$(SONAR_PROJECT_VERSION)
      sonar.host.url=$(SONARQUBE_SERVER)
      sonar.login=$(SONARQUBE_TOKEN)
  displayName: 'Prepare SonarQube Analysis'
- script: |
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
    unzip sonar-scanner-cli-4.6.2.2472-linux.zip
    export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
  displayName: 'Install SonarQube Scanner'

- script: |
    sonar-scanner \
      -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
      -Dsonar.projectName=$(SONAR_PROJECT_NAME) \
      -Dsonar.projectVersion=$(SONAR_PROJECT_VERSION) \
      -Dsonar.sources=. \
      -Dsonar.host.url=$(SONARQUBE_SERVER) \
      -Dsonar.login=$(SONARQUBE_TOKEN)
  displayName: 'Run SonarQube Analysis'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'
