trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_SERVER: 'https://sonar-dev.supervity.ai'
  SONARQUBE_TOKEN: '$(sqa_18ca7a4a75620b175378099dc7730a1eddf2a3b6)'
  SONAR_PROJECT_KEY: 'Infra-Test_Infra-Test_c5e09591-38a9-4945-855d-ef8425949b9b'
  SONAR_PROJECT_NAME: 'walmart-python'
  SONAR_PROJECT_VERSION: '1.0'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt.txt
  displayName: 'Install dependencies'

- script: |
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
    unzip sonar-scanner-cli-4.7.0.2747-linux.zip
    export PATH=$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin
  displayName: 'Install SonarQube Scanner'
- script: |
    export PATH=$PATH:/path/to/sonar-scanner/bin
  displayName: 'Add SonarQube Scanner to PATH'
- script: sonar-scanner
  displayName: 'Run SonarQube Scanner'


- script: |
    sonar-scanner \
      -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
      -Dsonar.projectName=$(SONAR_PROJECT_NAME) \
      -Dsonar.projectVersion=$(SONAR_PROJECT_VERSION) \
      -Dsonar.sources=. \
      -Dsonar.host.url=$(SONARQUBE_SERVER) \
      -Dsonar.login=$(SONARQUBE_TOKEN)
  displayName: 'Run SonarQube Analysis'

- script: |
    echo "Running tests..."
    # Example test command; replace with your actual test command
    pytest
  displayName: 'Run tests'
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Infra-Test_Infra-Test_c5e09591-38a9-4945-855d-ef8425949b9b'
    cliProjectName: 'walmart-python'
    cliSources: '.'
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'